jkroepke/openvpn-auth-oauth2

.github/workflows/ci.yaml
.github/workflows/pr-check.yaml

Add PR label checker

---

docs/Configuration.md
internal/config/config.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #34 

fix docs CONFIG_HTTP_BASEURL

---

go.mod
go.sum
internal/oauth2/handler_test.go

Remove gorilla/mux dependency

---

cmd/root.go
cmd/root_test.go
internal/oauth2/handler.go
internal/oauth2/handler_test.go
internal/openvpn/main.go

Add graceful shutdown to http listener

---

.github/workflows/ci.yaml
.goreleaser.yaml
plugin/Dockerfile

Add arm64 plugin builds

---

.github/workflows/ci.yaml
.goreleaser.yaml
internal/openvpn/client.go
internal/openvpn/main.go
internal/openvpn/main_test.go
packaging/config.yaml
packaging/preremove.sh

Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>**What this PR does / why we need it**:

CI: test release in CI

---

internal/http/main.go
internal/oauth2/providers/github/endpoints.go

Manual configuration of token url

---

internal/config/config.go
internal/config/defaults.go
internal/config/types.go
internal/openvpn/client.go
pkg/plugin/plugin.go

Add openvpn.auth-pending-timeout flag

---

internal/oauth2/handler.go
internal/oauth2/providers/github/endpoints.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49 

Fixed go panic with GitHub provider

---

internal/config/config.go
internal/config/decode_hooks.go
internal/config/decode_hooks_test.go
internal/config/types.go
internal/oauth2/handler.go
internal/oauth2/handler_test.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54 

Fix --html.template option

---

.github/workflows/ci.yaml

fix goreleaser tag

---

.goreleaser.yaml

CI: Enable verified builds

---

go.mod
go.sum
internal/oauth2/provider_test.go
pkg/testutils/main.go

ci: fix race issues

---

go.sum
internal/state/state.go
internal/state/state_test.go

Reduce state size

---

internal/oauth2/handler.go
internal/oauth2/idtoken/main.go
internal/oauth2/providers/generic/check.go
internal/oauth2/providers/generic/check_test.go
internal/oauth2/providers/generic/user.go
internal/oauth2/providers/github/check.go
internal/oauth2/providers/github/user.go
internal/oauth2/types.go

Use minimal token interface to ignore non compliant token claims

---

docs/Providers.md

Adding Google Workspace / Google Cloud as working provider, out-of-the-box with no special behavior.

Adding Google Workspace / Google Cloud as working provider

---

cmd/root.go
internal/config/config.go
internal/config/defaults.go
internal/config/types.go
internal/oauth2/handler.go
internal/oauth2/handler_test.go
internal/oauth2/provider.go
internal/oauth2/provider_test.go
internal/oauth2/types.go
internal/openvpn/main.go
internal/openvpn/main_test.go
internal/openvpn/types.go
internal/storage/errors.go
internal/storage/storage.go
pkg/plugin/plugin.go

Implement token store

---

internal/openvpn/connection/bench_test.go
internal/openvpn/connection/client.go

Optimize connection parser

---

Makefile
cmd/root_test.go
internal/internal_test.go
internal/oauth2/handler.go
internal/oauth2/provider.go
internal/oauth2/provider_test.go
internal/oauth2/providers/generic/refresh.go
internal/oauth2/providers/github/refresh.go
internal/oauth2/refresh.go
internal/oauth2/refresh_test.go
internal/oauth2/types.go
internal/openvpn/client.go
internal/openvpn/handler.go
internal/openvpn/main.go
pkg/testutils/main.go

Support session refresh for Github Provider

---

docs/Configuration.md

docs: Add HTTPS listener

---

docs/Configuration.md
docs/_Footer.md
internal/config/config.go

add doc not about `oauth2.refresh.secret`

---

cmd/root_test.go
internal/oauth2/handler_test.go
internal/openvpn/handler.go
internal/openvpn/main.go
internal/openvpn/main_test.go
internal/openvpn/types.go

try fix tests

---

internal/oauth2/handler.go
internal/oauth2/provider.go
internal/openvpn/client.go

Fixes error `http: named cookie not present ` with Safari Browser
- fixes #107 

fix error named cookie not present on Safari Browser

---

internal/config/config.go
internal/oauth2/handler_test.go
internal/oauth2/provider.go
internal/oauth2/refresh.go
internal/openvpn/main.go

implements tests for cookie behavior

---

cmd/root.go
docs/Configuration.md
docs/Installation.md
docs/Providers.md
go.mod
go.sum
internal/oauth2/provider.go
internal/oauth2/provider_test.go
internal/oauth2/providers/generic/refresh.go
internal/oauth2/providers/github/check.go
internal/oauth2/providers/github/endpoints.go
internal/oauth2/refresh.go
pkg/plugin/go.mod
pkg/plugin/go.sum
pkg/plugin/plugin.go
pkg/testutils/main.go
tests/systemd/docker-compose.yaml

fix typo and debugging

---

Makefile
cmd/root.go
internal/config/decode_hooks.go
internal/oauth2/handler.go
internal/oauth2/provider.go
internal/oauth2/refresh.go
internal/openvpn/bench_test.go
internal/openvpn/main.go

Add an error id for user assistance.

---

go.mod
go.sum
go.work.sum
internal/oauth2/refresh.go
pkg/plugin/go.mod
pkg/plugin/go.sum

Use rp.ErrRelyingPartyNotSupportRevokeCaller

---

internal/oauth2/idtoken/main.go
internal/oauth2/provider.go
internal/oauth2/providers/generic/check.go
internal/oauth2/providers/generic/check_test.go

Fix ipaddr validation

---

cmd/daemon/root.go
cmd/daemon/root_test.go
cmd/state/root.go
internal/oauth2/handler.go
internal/state/state.go
internal/state/state_test.go
main.go
tests/docker-compose.yaml

Improve state errors

---

internal/state/state.go
internal/state/state_test.go

Improve state scan errors

---

internal/openvpn/connection/client.go
pkg/plugin/client.go

Enables handling of connections from clients using the current generation of the IP protocol.
https://github.com/jkroepke/openvpn-auth-oauth2/issues/125
This is a minimal proof of concept, just with minimum manual testing. I have not updated the automated tests.

Fix connections from IPv6 clients

---

internal/oauth2/handler.go

HTTP: restrict methods to GET

---

.golangci.yaml
docs/Configuration.md
internal/config/config.go
internal/config/types.go
internal/httpserver/main_test.go
internal/internal_test.go
internal/oauth2/handler.go
internal/oauth2/handler_test.go
internal/oauth2/provider.go
internal/oauth2/provider_test.go
internal/oauth2/refresh_test.go
internal/openvpn/bench_test.go
internal/openvpn/main_test.go
pkg/testutils/logger.go
pkg/testutils/main.go

Implement acr verifier

---

docs/Providers.md

Update Providers.md with consent for preexisting Google app

---

docs/Configuration.md

Mention `auth-user-pass-optional`

---

packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service

Disable syscall filter

---

docs/Debugging Errors.md
docs/Providers.md

Add more details docs to GCP Provider

---

docs/Providers.md

Add keycloak docs

---

internal/openvpn/passthrough.go

Use \r\n as new-line separator and ignore quit

---

docs/Configuration.md
internal/config/config.go
internal/config/load_test.go
internal/config/types.go
internal/oauth2/providers/generic/check.go
internal/oauth2/providers/generic/check_test.go

Check common name in case sensitive mode by default

---

.codecov.yml
cmd/daemon/root.go
cmd/daemon/root_test.go
docs/Configuration.md
internal/httpserver/main.go
internal/httpserver/main_test.go
pkg/plugin/main.go
pkg/testutils/main.go
tests/docker-compose.yaml

Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>#### What this PR does / why we need it
- closes #160 

Reload TLS certificate on SIGHUP

---

internal/oauth2/handler_test.go
internal/oauth2/providers/github/api.go
internal/oauth2/providers/github/check.go
internal/oauth2/providers/github/check_test.go
internal/oauth2/providers/github/user.go
internal/oauth2/providers/github/user_test.go
internal/oauth2/providers/google/api.go
internal/oauth2/providers/google/check_test.go
internal/openvpn/passthrough_test.go
pkg/testutils/http.go
pkg/testutils/main.go

Increase test coverage

---

internal/openvpn/connection/client.go
internal/openvpn/connection/client_test.go

Log client IP

---

docs/Configuration.md
internal/config/config.go
internal/config/defaults.go
internal/config/load_test.go
internal/config/types.go
internal/openvpn/client.go
packaging/etc/openvpn-auth-oauth2/config.yaml

Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>#### What this PR does / why we need it
- fixes #

Add --log.vpn-client-ip

---

internal/oauth2/providers/generic/check_test.go
internal/oauth2/providers/generic/user.go
internal/oauth2/providers/github/user_test.go

Added nil check to Check functions

---

.github/workflows/ci.yaml
.gitignore
.goreleaser.yaml
Makefile

add 3rdpartylicenses

---

.github/workflows/ci.yaml
.goreleaser.yaml

add 3rdpartylicenses with goreleaser

---

go.mod
go.sum
go.work.sum
pkg/plugin/go.mod
pkg/plugin/go.sum

bump dependencies

---

internal/openvpn/bench_test.go
internal/openvpn/main_test.go
internal/openvpn/passthrough.go
internal/openvpn/passthrough_test.go
internal/openvpn/types.go

passthrough: Add welcome message

---

.github/workflows/ci.yaml
.goreleaser.yaml

Provide BSD builds

---

.github/workflows/ci.yaml
Makefile
internal/openvpn/bench_test.go
internal/openvpn/handler.go
internal/openvpn/passthrough.go
internal/openvpn/passthrough_test.go
renovate.json

passthrough: fix status 2+3 commands

---

.gitignore
cmd/daemon/root.go
internal/oauth2/providers/google/api.go
internal/oauth2/providers/google/config.go
internal/openvpn/handler.go
tests/Dockerfile
tests/docker-compose.yaml
tests/systemd/docker-compose.yaml

openvpn: fix hang on invalid password

---

.goreleaser.yaml
packaging/etc/apparmor.d/usr.bin.openvpn-auth-oauth2
packaging/scripts/postinst.sh
packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service
tests/systemd/Dockerfile
tests/systemd/docker-compose.yaml

systemd: Enable hardenings

---

packaging/etc/apparmor.d/usr.bin.openvpn-auth-oauth2
packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service

Fix read files in etc dir

---

.editorconfig
packaging/scripts/postinst.sh
packaging/scripts/postremove.sh
packaging/scripts/preremove.sh

DEB/RPM: Do not remove system group on upgrade

---

.run/go test openvpn-auth-oauth2.run.xml
internal/openvpn/connection/client.go
internal/openvpn/handler.go
internal/openvpn/main_test.go
internal/openvpn/passthrough_test.go

Remove command whitelist

---

cmd/daemon/root.go
cmd/state/root.go
internal/oauth2/handler.go
internal/oauth2/handler_test.go
internal/oauth2/provider.go
internal/oauth2/provider_test.go
internal/openvpn/bench_test.go
internal/openvpn/client.go
internal/openvpn/main_test.go
internal/openvpn/passthrough_test.go
internal/state/bench_test.go
internal/state/state.go
internal/state/state_test.go
internal/storage/storage.go
internal/storage/storage_test.go
pkg/plugin/plugin.go
pkg/testutils/main.go

Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>#### What this PR does / why we need it
- fixes #

nit: add context to storage class

---

.golangci.yaml
cmd/daemon/full_test.go
cmd/daemon/it_test.go
docs/Layout Customization.md
internal/httpserver/main.go
internal/oauth2/providers/google/api.go
internal/openvpn/handler.go
internal/openvpn/passthrough.go
internal/ui/assets/mvp.css
pkg/plugin/README.md
pkg/testutils/http.go
pkg/testutils/main.go

test full command

---

docs/Providers.md
internal/oauth2/providers/google/api.go
internal/oauth2/providers/google/check.go
internal/oauth2/providers/google/check_test.go
internal/ui/assets/i18n/de.json

Provider: Google Groups: `oauth2.validate.groups` requires group ID instead group name

---

internal/openvpn/passthrough.go

fix deadline in pass-through after client disconnect

---

internal/openvpn/handler.go

fix: better error message against older OpenVPN versions

---

.github/workflows/spelling.yaml
docs/Home.md
docs/Providers.md
internal/openvpn/main.go
internal/state/state_test.go

Add CI for spell

---

docs/Configuration.md
internal/config/flags.go

breaking: rename --openvpn.common-name.environment-variable to --openvpn.common-name.environment-variable-name

---

.editorconfig
cmd/daemon/root.go
cmd/daemon/root_test.go
docs/Configuration.md
docs/Debugging Errors.md
docs/Filesystem Permissions.md
docs/HTTPS Listener.md
docs/Management Interface pass-through.md
docs/Non-interactive session refresh.md
docs/Providers.md
internal/httpserver/main.go
internal/httpserver/main_test.go
internal/oauth2/providers/google/config.go
packaging/etc/apparmor.d/usr.bin.openvpn-auth-oauth2
packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service
pkg/plugin/plugin.go

- fixes #304
- fixes #305
- fixes #292

docs: add default settings to docs

---

docs/OpenVPN.md

Fixes a duplicated header in the documentation.

Remove duplicated string in Documentation

---

packaging/etc/apparmor.d/usr.bin.openvpn-auth-oauth2

fix mime types access

---

docs/HTTPS Listener.md

PR helps users to generate cert for https with certbot. I saw your note [here](https://github.com/jkroepke/openvpn-auth-oauth2/blob/440936ca35bf5392a94a84eec8f834c47d24d072/docs/HTTPS%20Listener.md?plain=1#L65) and wanted to contribute. 
If you have any comments on the PR please give a feedback

Add some certbot instructions in wiki

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/enhancement.yaml
.github/ISSUE_TEMPLATE/question.yaml
docs/Configuration.md
docs/FAQ.md
docs/Layout Customization.md
internal/config/flags.go
internal/config/flags_test.go
internal/config/validate.go

Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>#### What this PR does / why we need it
- ref #361 

Clarify docs

---

cmd/daemon/root.go
cmd/daemon/root_test.go

small lint fixes

---

docs/Configuration.md

docs: fix type `CONFIG_HTTP_BASE_URL` -> `CONFIG_HTTP_BASEURL`

---

cmd/daemon/root.go
internal/openvpn/main.go
internal/openvpn/passthrough.go

passthrough: fix instabilities

---

.github/workflows/ci.yaml

pin version of go ci linter

---

.goreleaser.yaml

remove deprecated settings

---

.gitignore
.run/go test openvpn-auth-oauth2.run.xml
cmd/daemon/full_test.go
internal/config/load_test.go
internal/httphandler/handler_test.go
internal/oauth2/provider_test.go
internal/oauth2/refresh_test.go
internal/openvpn/bench_test.go
internal/openvpn/main_test.go
internal/openvpn/passthrough_test.go
internal/tokenstorage/inmemory_test.go
internal/utils/http_test.go

fix: tests

---

cmd/daemon/root.go
internal/httphandler/handler.go
internal/httphandler/handler_test.go
internal/oauth2/provider_test.go
internal/utils/testutils/main.go

make assets directory configurable again

---

internal/openvpn/passthrough.go

fix race condition in pass-through client

---

packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service

feat: Add reload command for systemd

---

internal/config/config.go
internal/config/env_test.go
tests/docker-compose.yaml

fix config load via env variables

---

internal/config/config.go
internal/openvpn/main.go
internal/openvpn/types.go

Add locking to prevent deadlocks

---

.editorconfig-checker.json
.github/workflows/ci.yaml

fix editorconfig-checker

---

.gitignore
internal/state/state.go
internal/state/types.go
renovate.json

chore: optimize state decode/encode functions

---

cmd/daemon/root.go
internal/config/config.go
internal/config/types.go
internal/oauth2/refresh.go
internal/openvpn/bench_test.go
internal/openvpn/main_test.go
internal/openvpn/passthrough_test.go
internal/tokenstorage/inmemory.go
internal/tokenstorage/inmemory_test.go
internal/tokenstorage/types.go
internal/utils/testutils/main.go
internal/utils/testutils/storage.go
packaging/usr/lib/systemd/system/openvpn-auth-oauth2.service

feat: add soft-reload

---

cmd/daemon/full_test.go
cmd/daemon/reload_test.go
internal/config/config_test.go
internal/internal_test.go
internal/oauth2/handler_test.go
internal/oauth2/provider_test.go
internal/oauth2/refresh_test.go
internal/utils/testutils/main.go

chore: add test non working refresh

---

.golangci.yaml
cmd/daemon/full_test.go
cmd/daemon/root.go
cmd/daemon/root_test.go
internal/config/config_test.go
internal/config/validate_test.go
internal/httpserver/main_test.go
internal/oauth2/provider_test.go
internal/oauth2/providers/generic/check_test.go
internal/oauth2/providers/github/check_test.go
internal/oauth2/providers/github/user_test.go
internal/oauth2/providers/google/check_test.go
internal/oauth2/refresh.go
internal/openvpn/bench_test.go
internal/openvpn/connection/client_test.go
internal/openvpn/passthrough_test.go
internal/utils/common_name_test.go
internal/utils/lookup_test.go

rector main function

---

cmd/daemon/root.go
internal/config/validate_test.go
internal/tokenstorage/inmemory.go
internal/tokenstorage/inmemory_test.go

chore: test coverage

---

docs/Configuration.md
docs/Providers.md
internal/config/flags.go
packaging/etc/openvpn-auth-oauth2/config.yaml

docs: add new cli parameters to docs

---

.github/workflows/ci.yaml
.goreleaser.yaml

Ref: https://goreleaser.com/customization/attestations/
- fixes #

feat: added supply-chain attestation

---

docs/Non-interactive session refresh.md

Removed old AI scaffold text 
None.
None.
Updating docs/wiki page

docs: Remove AI scaffold text from Non-interactive session refresh.md

---

DEVELOPER.md
go.mod

feat: update to go 1.25

---

go.mod
go.sum
internal/config/config.go
internal/config/types/slice_test.go
internal/config/types/template_test.go
internal/config/types/url_test.go

chore: use go.yaml.in/yaml/v3

---

.github/workflows/tag.yaml

create tag workflow
